// react/my-react-project/src/screens/BookList/components/Book/index.js
import React from 'react';

import styles from './styles.module.scss';

function Book({ book }) {
  return (
    <div className={styles.bookContainer} key={book.id}>
      <img className={styles.bookImage} src={book.img} alt={book.title} />
      <h4 className={styles.bookTitle}>{book.title}</h4>
      <h6 className={styles.bookAuthor}>{book.author}</h6>
    </div>
  );
}

export default Book;

// angular/tech-show-frontend/src/app/components/book/book.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.scss']
})
export class BookComponent implements OnInit {
  @Input() book: any;

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
  <img [src]="book.img" alt="" />
  <h4>{{ book.title }}</h4>
  <span>{{ book.author }}</span>
</div>
